### ISSUE TITLE
Does kops-cn has GPU support?

### ISSUE THREAD

**Issue by liangfb** [nwcdlabs/kops-cn#108]
Hi, We have lots of Deep Learning workload on K8S. If I provision the cluster by kops-cn on AWS China region, How to enable the GPU(Tesla V100) support on worker nodes?

Thanks!

**Comment by pahud** [comment]
kops-cn is just kops with some recommended configuration and image mirrors.

You will need to check this upstream document about kops with gpu support.

https://github.com/kubernetes/kops/blob/master/docs/gpu.md
