### ISSUE TITLE
docker mirror docker-cn.com 已经不能使用了

### ISSUE THREAD

**Issue by JoeShi** [nwcdlabs/kops-cn#110]
Hi,

我看到在 spec.yml 里面写的 docker mirror 是 docker-cn.com， 但这个 mirror site 已经在几个月前就不能用了。

related issue: https://github.com/docker/docker.github.io/issues/8793

**Comment by pahud** [comment]
感謝，我關注一下這個issue，另外，有建議的其他替代mirror源嗎？

cc @walkley

**Comment by JoeShi** [comment]
中科大
http://mirrors.ustc.edu.cn/help/dockerhub.html?highlight=docker

[网易镜像中心](https://c.163yun.com/hub#/m/home/)
https://hub.c.163.com

**Comment by pahud** [comment]
<img width="1287" alt="圖片" src="https://user-images.githubusercontent.com/278432/63645923-db224e80-c73a-11e9-8676-e4789e69756d.png">

我剛從寧夏EC2測試了一下，維持原本`registry.docker-cn.com`的配置，似乎一開始不會馬上下載，隔了幾秒之後就能成功下載

**Comment by pahud** [comment]
我試著換了 `https://docker.mirrors.ustc.edu.cn` 感覺效果差不多

有誰用了 `registry.docker-cn.com` 之後node無法docker pull Docker Images嗎？

**Comment by JoeShi** [comment]
这是我的尝试，在ZHY区域。
<img width="1414" alt="Screen Shot 2019-08-26 at 12 01 18 AM" src="https://user-images.githubusercontent.com/2173635/63652612-c2468700-c794-11e9-8eea-8abb0dc34e15.png">

第一次尝试是530，第二次尝试也是失败，并且出现了 cloudflare 的CDN. 感觉不像是从国内拉的。

另外我在本地尝试 `telnet registry.docker-cn.com 443` 是不通的。`telnet hub.c.163.com 443` 是OK的。

**Comment by pahud** [comment]
暫時改成用163。
