### ISSUE TITLE
How to get the node profile after create cluster

### ISSUE THREAD

**Issue by zhang-zhenqing** [nwcdlabs/kops-cn#117]
已经根据文档在宁夏区建立了k8s cluster， 接下来想去配置alb，但是文档不是很清楚，望给与解答：
https://github.com/nwcdlabs/kops-cn/blob/master/doc/aws-alb-ingress_en.md

$ aws --profile **bjs** iam list-roles | grep "nodes.cluster"
            "RoleName": "nodes.cluster.zhy.k8s.local",
            "Arn": "arn:aws-cn:iam::937788672844:role/nodes.cluster.zhy.k8s.local"
Attach iam-policy.json as extra role policy to the node role.
aws --profile **bjs** iam put-role-policy --role-name nodes.cluster.zhy.k8s.local --policy-name alb-ingress-extra --policy-document file://iam-policy.json

这里面的profile **bjs**， 怎么来的？ 如果是cluster.bjs.k8s.local中的bjs，似乎是不对的，没有这个profile

**Comment by pahud** [comment]
不需要這個--profile bjs， 只要確保你當前AWS CLI profile是使用國內region的配置即可。

我把這 --profile 拿掉吧。

**Comment by pahud** [comment]
另外，這份文件有點舊了，建議對照上游官方文件一起看

https://github.com/kubernetes-sigs/aws-alb-ingress-controller

**Comment by zhang-zhenqing** [comment]
对的，不要是可以的，多谢
