### ISSUE TITLE
kops can't update to the latest of 1.13 for 1.13.12

### ISSUE THREAD

**Issue by williamyao1982** [nwcdlabs/kops-cn#120]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.13.0
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.12.9
**3. What AWS region are you using(Beijing or Ningxia)?**
Beijing
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
I already updated to 1.13.10. But not the latest version. But the package doesn't exist in S3.
**5. What happened after the commands executed?**
It mentioned the 1.13.12 package doesn't exist in S3.
**6. What did you expect to happen?**
I hope we can updated to 1.13.12.
**7. Please provide the content of your `Makefile` and how did you run the `make` command
  You may want to remove your cluster name and other sensitive information.**

**8. Anything else do we need to know?**

**Comment by pahud** [comment]
OK I will prepare for it

https://github.com/kubernetes/kops/blob/1eb9b7d5d28d1c8c3fbd95bcd6079bf8a3928a4b/channels/stable#L60-L62

**Comment by pahud** [comment]
mirror complete

**Comment by pahud** [comment]
mirror completed

**Comment by williamyao1982** [comment]
Now the cluster has been upgraded to 1.13.12. Thanks a lot!
