### ISSUE TITLE
docker repository for Amazon VPC CNI

### ISSUE THREAD

**Issue by walkley** [nwcdlabs/kops-cn#18]
**Symptom**
Deploy kops with Amazon VPC CNI(--networking=amazon-vpc-routed-eni), the daemonset aws-node will be failed due to ImagePullBackOff.

**Root Cause**
The generated image url of aws-node is invalid: 
937788672844.dkr.ecr.cn-north-1.amazonaws.com.cn/602401143452.dkr.ecr.us-west-2.amazonaws.com-amazon-k8s-cni:1.0.0

From the [yaml template](https://github.com/kubernetes/kops/blob/v1.10.0/upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.7.yaml.template#L70), image url will be generated from parameter "Networking.AmazonVPC.ImageName" or the default image url from us-west-2 ECR. 

It works well after changing image url of aws-node to "pahud/amazon-k8s-cni:1.0.0"

**Suggested Solution**

1. Specify "Networking.AmazonVPC.ImageName" in kops edit as following:
  networking:
    amazonvpc:
      imageName: amazon-k8s-cni:1.0.0
2. Add image amazon-k8s-cni:1.0.0 in docker registry 937788672844.dkr.ecr.cn-north-1.amazonaws.com.cn

**Comment by pahud** [comment]
> Failed to pull image "937788672844.dkr.ecr.cn-north-1.amazonaws.com.cn/602401143452.dkr.ecr.us-west-2.amazonaws.com-amazon-k8s-cni:1.0.0": rpc error: code = Unknown desc = Error response from daemon: pull access denied for 937788672844.dkr.ecr.cn-north-1.amazonaws.com.cn/602401143452.dkr.ecr.us-west-2.amazonaws.com-amazon-k8s-cni, repository does not exist or may require 'docker login'


The image URL is correct but I noticed the ECR repository access policy is wrong. I've fixed this issue and add the repository for public pull. Please try again.

**Comment by walkley** [comment]
Now it works!
Thank you Pahud.
