### ISSUE TITLE
How is secret managed? 

### ISSUE THREAD

**Issue by yujunz** [nwcdlabs/kops-cn#20]
Where do you store `$ak_kms_cipherblob`? Not quite familiar with CodeBuild.

https://github.com/nwcdlabs/kops-cn/blob/448b5fc45d47d525c9db6c6e54dfbb19a34b1c73/mirror/codebuild/bin/bjs_ecr_auth.sh#L6

**Comment by pahud** [comment]
I saved it in the CodeBuild project environment variables

![image](https://user-images.githubusercontent.com/278432/49152993-5cd18100-f34f-11e8-882a-73e93398a0df.png)

However, actually it's recommended to retrieve the parameters straight from the `parameter-store`.

Check the sample here - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax

**Comment by pahud** [comment]
I just updated and use the native parameter-store integration instead. 

see https://github.com/nwcdlabs/kops-cn/commit/6a13f9d831c6c68792ba04219a06b97a4013ff26

FYR
