### ISSUE TITLE
please upgrade helm docker version in reg to latest 2.11.0

### ISSUE THREAD

**Issue by lenew** [nwcdlabs/kops-cn#23]
when trying to use 'helm ls',
got this error "Error: incompatible versions client[v2.11.0] server[v2.9.1]"

**Comment by pahud** [comment]
please make sure you upgrade helm both the server and client version to v2.11.0

and  kubectl set image to tag 2.11.0

see: https://github.com/nwcdlabs/kops-cn/commit/288a62bcdccaef59b5d381ca06db4fbba6443552
