### ISSUE TITLE
How to use customized nodeup binary ?

### ISSUE THREAD

**Issue by yujunz** [nwcdlabs/kops-cn#35]
We need to use a customized nodeup for our cluster. When I try to override the default URL with

```
export NODEUP_URL='https://s3-us-west-2.amazonaws.com/my-bucket/nodeup/linux/amd64/01/23/18/1516747024/nodeup'
```

It seems hijacked by the `fileRepository` setting.

```
I1214 16:28:21.474161   94429 builder.go:297] error reading hash file "https://s3.cn-north-1.amazonaws.com.cn/kops-bjs/fileRepository/my-bucket/nodeup/linux/amd64/01/23/18/1516747024/nodeup.sha1": file does not exist

you may have not staged your files correctly, please execute kops update cluster using the assets phase
```

Any suggestions?

**Comment by pahud** [comment]
I haven't look into the source code yet, but I believe `fileRepository` will override `NODEUP_URL`.  In this case, you might have two options:

1.  maintain your own `fileRepository` yourself, and put your customized nodeup in your `fileRepository`

2. remove `fileRepository` in your `spec.yml` and use `NODEUP_URL` instead.

But either way you may still have some other issues need to look into.

**Comment by yujunz** [comment]
> * maintain your own `fileRepository` yourself, and put your customized nodeup in your `fileRepository`

Gonna try this way. Is https://github.com/nwcdlabs/kops-cn/blob/master/mirror/fileRepository/mirro.sh the easy way to do it?

> * remove `fileRepository` in your `spec.yml` and use `NODEUP_URL` instead.

Then we will like met access issue on the original repository, right? That's why we need to make a mirror I guess.

**Comment by yujunz** [comment]
> I haven't look into the source code yet, but I believe `fileRepository` will override `NODEUP_URL`

That's is probably true. It is always remapped as shown in https://github.com/kubernetes/kops/blob/1.10.0/upup/pkg/fi/cloudup/urls.go#L122
