### ISSUE TITLE
compatibility with AWS VPC CNI 1.3

### ISSUE THREAD

**Issue by pahud** [nwcdlabs/kops-cn#39]
Amazon EKS now supports AWS VPC CNI 1.3

https://docs.aws.amazon.com/en_us/eks/latest/userguide/cni-upgrades.html

Let's make sure kops-cn goes well with CNI 1.3

**Comment by walkley** [comment]
I've validated that kops-cn works well with AWS VPC CNI 1.3.

Two approaches to use CNI 1.3:
1. Create cluster from scratch:
  `kops edit cluster $cluster_name`
  then insert following settings under spec section:
  ```
networking:
    amazonvpc:
      imageName: 937788672844.dkr.ecr.cn-north-1.amazonaws.com.cn/602401143452.dkr.ecr.us-west-2.amazonaws.com-amazon-k8s-cni:1.3.0
  ```
2. Upgrade current cluster from lower version:
`kubectl edit daemonset aws-node -n kube-system`
`image: 937788672844.dkr.ecr.cn-north-1.amazonaws.com.cn/602401143452.dkr.ecr.us-west-2.amazonaws.com-amazon-k8s-cni:1.3.0`

**Comment by pahud** [comment]
Thanks a lot @walkley

**Comment by pahud** [comment]
adding `v1.3.2` image - https://github.com/nwcdlabs/kops-cn/commit/418ac6b9c20cad48b2d03e5871031a1dbb1e90c0
