### ISSUE TITLE
默认的配置，dns controller启动失败

### ISSUE THREAD

**Issue by andybrier** [nwcdlabs/kops-cn#43]
dns controller启动失败， kope/dns-controller:  1.11.0  找不到

**Comment by pahud** [comment]
我看到這個PR了
https://github.com/kubernetes/kops/pull/6256/files 看起來是1.11.0沒錯

**Comment by pahud** [comment]
1.11.0開始mirror了，大約半小時之後請再試試看，如果還有缺少其他images請把完整信息貼過來這裡，謝謝！

**Comment by pahud** [comment]
應該沒問題了

https://github.com/nwcdlabs/kops-cn/issues/42#issuecomment-451496627
