### ISSUE TITLE
k8s.gcr.io/kube-proxy:v1.11.6 is missing

### ISSUE THREAD

**Issue by bigdrum** [nwcdlabs/kops-cn#49]
After upgrading to 1.11.6, the kube-proxy pod failed to come up since this image is mirrored. (I guess it is the same for many other 1.11.6 image)

I wonder if we can just have automatic script to enumerate all versions of the white listed images and make a mirror of it, so that we don't need to worry about that any more.

**Comment by pahud** [comment]
thanks for your feedback

Have fixed the missing images
https://github.com/nwcdlabs/kops-cn/commit/5b06afd63bd856cbed96da585f4fc60f95f7f876
