### ISSUE TITLE
Run create-cluster.sh faild

### ISSUE THREAD

**Issue by bwboy** [nwcdlabs/kops-cn#51]
I run the install on my mac.
when I had configured env.config and run the create-cluster.sh, I got the error msg below:

I0130 10:08:37.058539    5466 create_cluster.go:1407] Using SSH public key: /Users/wangqi/.ssh/id_rsa
I0130 10:08:38.840289    5466 subnets.go:184] Assigned CIDR 172.0.32.0/19 to subnet cn-northwest-1a
I0130 10:08:38.840325    5466 subnets.go:184] Assigned CIDR 172.0.64.0/19 to subnet cn-northwest-1b
I0130 10:08:38.840362    5466 subnets.go:184] Assigned CIDR 172.0.96.0/19 to subnet cn-northwest-1c

error determining default DNS zone: error querying zones: RequestError: send request failed
caused by: Get https://route53.cn-northwest-1.amazonaws.com.cn/2013-04-01/hostedzone: dial tcp: lookup route53.cn-northwest-1.amazonaws.com.cn on 172.20.53.163:53: no such host

**Comment by pahud** [comment]
@seimutig can you help look into this issue?

**Comment by bwboy** [comment]
here is the env.config

#!/bin/bash

# deploy to Beijing region(cn-north-1) or NingXia region(cn-northwest-1)
#TARGET_REGION='cn-north-1'
TARGET_REGION='cn-northwest-1'
AWS_DEFAULT_REGION='cn-northwest-1'

# change this to your aws-cli profile name for AWS China
export AWS_PROFILE=${AWS_PROFILE-default}
export AWS_DEFAULT_REGION=${TARGET_REGION}
export AWS_REGION=${AWS_DEFAULT_REGION}
# change this to your S3 bucket
export KOPS_STATE_STORE=s3://kops-0129

# define the version number
KUBERNETES_VERSION='v1.11.6'
KOPS_VERSION='1.11.0'
#KUBERNETES_VERSION_URL="https://s3.cn-north-1.amazonaws.com.cn/kubernetes-release/release/$KUBERNETES_VERSION"


case "$TARGET_REGION" in
    cn-north-1)
        cluster_name=${cluster_name-cluster.bjs.k8s.local}
        ami='ami-0a957d1aa321cd9b0'
        zones='cn-north-1a,cn-north-1b'
        ;;
    cn-northwest-1)
        cluster_name=${cluster_name-cluster.zhy.k8s.gavin}
        ami='ami-01c805b12c4107d92'
        zones='cn-northwest-1a,cn-northwest-1b,cn-northwest-1c'
        ;;
    *)
        echo "invalid TARGET_REGION: $TARGET_REGION"
        exit 1
        ;;
esac

# customize the values below
vpcid='vpc-09f26ce1464301be5'
#vpcid='vpc-c1e040a5'
master_count=3
master_size='t2.medium'
node_size='t2.medium'
node_count=2
ssh_public_key='/Users/gavin/.ssh/id_rsa'

**Comment by bwboy** [comment]
here is file 
`
#!/bin/bash

# deploy to Beijing region(cn-north-1) or NingXia region(cn-northwest-1)
#TARGET_REGION='cn-north-1'
TARGET_REGION='cn-northwest-1'
AWS_DEFAULT_REGION='cn-northwest-1'

# change this to your aws-cli profile name for AWS China
export AWS_PROFILE=${AWS_PROFILE-default}
export AWS_DEFAULT_REGION=${TARGET_REGION}
export AWS_REGION=${AWS_DEFAULT_REGION}
# change this to your S3 bucket
export KOPS_STATE_STORE=s3://kops-0129

# define the version number
KUBERNETES_VERSION='v1.11.6'
KOPS_VERSION='1.11.0'
#KUBERNETES_VERSION_URL="https://s3.cn-north-1.amazonaws.com.cn/kubernetes-release/release/$KUBERNETES_VERSION"


case "$TARGET_REGION" in
    cn-north-1)
        cluster_name=${cluster_name-cluster.bjs.k8s.local}
        ami='ami-0a957d1aa321cd9b0'
        zones='cn-north-1a,cn-north-1b'
        ;;
    cn-northwest-1)
        cluster_name=${cluster_name-cluster.zhy.k8s.gavin}
        ami='ami-01c805b12c4107d92'
        zones='cn-northwest-1a,cn-northwest-1b,cn-northwest-1c'
        ;;
    *)
        echo "invalid TARGET_REGION: $TARGET_REGION"
        exit 1
        ;;
esac

# customize the values below
vpcid='vpc-09f26ce1464301be5'
#vpcid='vpc-c1e040a5'
master_count=3
master_size='t2.medium'
node_size='t2.medium'
node_count=2
ssh_public_key='/Users/wangqi/.ssh/id_rsa'
`

**Comment by bwboy** [comment]
here is the file
```
#!/bin/bash

# deploy to Beijing region(cn-north-1) or NingXia region(cn-northwest-1)
#TARGET_REGION='cn-north-1'
TARGET_REGION='cn-northwest-1'
AWS_DEFAULT_REGION='cn-northwest-1'

# change this to your aws-cli profile name for AWS China
export AWS_PROFILE=${AWS_PROFILE-default}
export AWS_DEFAULT_REGION=${TARGET_REGION}
export AWS_REGION=${AWS_DEFAULT_REGION}
# change this to your S3 bucket
export KOPS_STATE_STORE=s3://kops-0129

# define the version number
KUBERNETES_VERSION='v1.11.6'
KOPS_VERSION='1.11.0'
#KUBERNETES_VERSION_URL="https://s3.cn-north-1.amazonaws.com.cn/kubernetes-release/release/$KUBERNETES_VERSION"


case "$TARGET_REGION" in
    cn-north-1)
        cluster_name=${cluster_name-cluster.bjs.k8s.local}
        ami='ami-0a957d1aa321cd9b0'
        zones='cn-north-1a,cn-north-1b'
        ;;
    cn-northwest-1)
        cluster_name=${cluster_name-cluster.zhy.k8s.gavin}
        ami='ami-01c805b12c4107d92'
        zones='cn-northwest-1a,cn-northwest-1b,cn-northwest-1c'
        ;;
    *)
        echo "invalid TARGET_REGION: $TARGET_REGION"
        exit 1
        ;;
esac

# customize the values below
vpcid='vpc-09f26ce1464301be5'
#vpcid='vpc-c1e040a5'
master_count=3
master_size='t2.medium'
node_size='t2.medium'
node_count=2
ssh_public_key='/Users/wangqi/.ssh/id_rsa'
```

**Comment by seimutig** [comment]
hello Gavin, the  cluster name should be  end up with k8s.local

**Comment by pahud** [comment]
```
ssh_public_key='/Users/wangqi/.ssh/id_rsa'
```

還有這個應該不是public key, 一般應該是 `.pub`結尾才對。

**Comment by bwboy** [comment]
Thanks, @seimutig, and @pahud  the ".local" is the key to the issue.
and "id_rsa" is a mistake when I pasted the config file.

**Comment by pahud** [comment]
@bwboy Great！thanks！
