### ISSUE TITLE
Add more script to makefile

### ISSUE THREAD

**Issue by jansony1** [nwcdlabs/kops-cn#58]
As some of our customer may edit wrong in "make edit-cluster" step or they need to update their cluster, so they need rolling update options. Also, if they choose use makefile to doing their kops operation, we my better list all operations so that they **have no need to maintain another set of 
Environment variable.**

Here are two my customer requirement, so add it here.

.PHONY: rolling-cluster
rolling-cluster:
	@KOPS_STATE_STORE=$(KOPS_STATE_STORE) \
	AWS_PROFILE=$(AWS_PROFILE) \
        AWS_REGION=$(AWS_REGION) \
        AWS_DEFAULT_REGION=$(AWS_DEFAULT_REGION) \
        kops rolling-update cluster --name $(CLUSTER_NAME) --yes --cloudonly

.PHONY: get-cluster
get-cluster:
	@KOPS_STATE_STORE=$(KOPS_STATE_STORE) \
        AWS_PROFILE=$(AWS_PROFILE) \
        AWS_REGION=$(AWS_REGION) \
        AWS_DEFAULT_REGION=$(AWS_DEFAULT_REGION) \
        kops get cluster --name $(CLUSTER_NAME)

**Comment by pahud** [comment]
Agree! Can you cut a PR for this and let me just merge it?

**Comment by pahud** [comment]
https://github.com/nwcdlabs/kops-cn/pull/59

resolving the issue.
