### ISSUE TITLE
how to ssh the master or node

### ISSUE THREAD

**Issue by hhuchzh** [nwcdlabs/kops-cn#6]
after finish creating the cluster, when I use ssh
 "ssh -i ~/.ssh/id_rsa.pub admin@ip-xx-xx-xx-xx.cn-north-1.compute.internal"
to login the master or node, it need to input the password, what's the password?

**Comment by pahud** [comment]
As the AMI is CoreOS system, you should ssh login into the system like this

> ssh -i ~/.ssh/id_rsa core@EC2_PUBLIC_IP

and then you can check the system log with `journalctl`, e.g.
```
$ sudo journalctl -f
```
