### ISSUE TITLE
error parsing SSH public key: ssh: no key found

### ISSUE THREAD

**Issue by liuevan48** [nwcdlabs/kops-cn#68]
I run into following issues when creating the cluster
I0416 09:48:45.708089    3672 create_cluster.go:1407] Using SSH public key: /home/ec2-user/.ssh/id_rsa.pub

error reading cluster configuration "cluster.zhy.k8s.local": error reading s3://liuhongxi-kops-cn/cluster.zhy.k8s.local/config: Unable to list AWS regions: NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, default.
EC2RoleRequestError: no EC2 instance role found
caused by: EC2MetadataError: failed to make EC2Metadata request
caused by: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>

make: *** [create-cluster] Error 1

**Comment by liuevan48** [comment]
I fixed this issue, but it become a new issue as below:

[ec2-user@ip-10-0-1-198 kops-cn-master]$ make create-cluster
I0416 10:05:28.663147    4217 create_cluster.go:1407] Using SSH public key: /home/ec2-user/.ssh/id_rsa.pub
I0416 10:05:31.038374    4217 subnets.go:184] Assigned CIDR 10.0.32.0/19 to subnet cn-northwest-1a
I0416 10:05:31.038400    4217 subnets.go:184] Assigned CIDR 10.0.64.0/19 to subnet cn-northwest-1b
I0416 10:05:31.038407    4217 subnets.go:184] Assigned CIDR 10.0.96.0/19 to subnet cn-northwest-1c

error adding SSH public key: error fingerprinting SSH public key "admin": error parsing SSH public key: ssh: no key found

**Comment by pahud** [comment]
```
error adding SSH public key: error fingerprinting SSH public key "admin": error parsing SSH public key: ssh: no key found
```

Your public key file may be broken. Make sure your public key file exists and is valid in `/home/ec2-user/.ssh/id_rsa.pub`

**Comment by liuevan48** [comment]
It seems if we generate the public key from somewhere else and import to /home/ec2-user/.ssh/, it won't work. But if we generate the public key in EC2 directly by using "ssh-keygen", the key can be used.

**Comment by pahud** [comment]
yes, you need to generate your ssh keypair by

1. `ssh-keygen`
or
2. generate from your EC2 keypair console, downloading the `.pem` private key and use `ssh-keygen -f` to generate its public key

see this demo

![image](https://user-images.githubusercontent.com/278432/56250330-f0d48880-6063-11e9-89f2-ea530dd24b42.png)

**Comment by pahud** [comment]
updated the README doc to help understand how to generate a public key for kops
https://github.com/nwcdlabs/kops-cn/commit/afa8b7e14ed13dc7ff727b0a4db17f0c8d13d257
https://github.com/nwcdlabs/kops-cn/commit/44efd9defe4c8bea33f5b82eadcd3f0ec423dbe1
