### ISSUE TITLE
For CN mainland scenario without ICP recordal, could we have an internal ELB being used to kubectl internally ?

### ISSUE THREAD

**Issue by tid999** [nwcdlabs/kops-cn#72]
For CN mainland scenario without ICP recordal, could we have an internal ELB being used to kubectl internally ?

**Comment by pahud** [comment]
Can you update the content body and provide the info as detailed as possible?

**Comment by pahud** [comment]
try this

https://github.com/kubernetes/kops/issues/1097
https://github.com/kubernetes/kops/issues/4548#issuecomment-422072394
