### ISSUE TITLE
kops安装过程与安装之后的一般应用部署如何跟ECR鉴权

### ISSUE THREAD

**Issue by YuTingLiu** [nwcdlabs/kops-cn#78]
请注意，`kops-cn`是一个开源项目帮助用户更容易部署`kops`在AWS中国北京与宁夏区，`kops-cn`没有侵入式修改上游`kops`源代码，并且保持跟上游`kops`版本一致，因此大部分`kops-cn`遇到的功能性问题都会存在上游`kops`专案当中，在发布问题的时候请务必确定[查看并搜寻](https://github.com/kubernetes/kops/issues?utf8=%E2%9C%93&q=is%3Aissue+)了`kops`上游是否有人发布过同样的的问题，这里无法解决`kops`本身存在的问题或issue，如果它是一个`kops`本身的issue，请务必发布到[上游kops专案的issue](https://github.com/kubernetes/kops/issues)当中。

如果你很肯定这个issue只跟`kops-cn`有关，跟上游`kops`无关，请填写以下信息帮助我们定位问题与改进这个项目，并且尽可能提供截图给我们。

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.11.1 (git-0f2aa8d30)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:32:00Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
**3. What AWS region are you using(Beijing or Ningxia)?**
Beijing 
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
make edit-cluster
**5. What happened after the commands executed?**
`  docker:
    logDriver: ""
    registryMirrors:
    - https://registry.docker-cn.com
`
**6. What did you expect to happen?**
`  docker:
    logDriver: ""
    registryMirrors:
    - https://<awsacctid>.dkr.ecr.us-east-1.amazonaws.com
`

**7. Please provide the content of your `Makefile` and how did you run the `make` command
  You may want to remove your cluster name and other sensitive information.**

**8. Anything else do we need to know?**
How to use ECR when deploy service?

**Comment by pahud** [comment]
我不大懂你的問題，你希望做什麼事？遇到了什麼問題？

**Comment by YuTingLiu** [comment]
> 我不大懂你的問題，你希望做什麼事？遇到了什麼問題？

感谢回复，
我不懂如何配置kops默认使用ECR中的镜像。
比如，在配置`make edit-cluster`时，如何设置ECR的registryMirrors，ECR是有一个鉴权过程的。如何实现。
如果不是配置`make edit-cluster`时设置ECR地址，那么在拉取ECR的image时该如何写yaml文件。
谢谢

**Comment by pahud** [comment]
Kops配置過程在spec.assets裡面指定`containerRegistry`之後，kops安裝過程會以`containerRegistry`為指定的local mirror site，所有docker image pull會往這邊抓取

https://github.com/nwcdlabs/kops-cn/blob/3cf848fe72fb3bf6c171a32b760208c64bd065c5/spec.yml#L3

這解決了kops安裝過程所需要的images全部都往這個專案提供的ECR來獲取景象，而不需要訪問海外，讓Kops可以很方便在北京與寧夏兩個region安裝起來。

官方的containerRegistry說明參考這裡，主要是用來部署一個local mirror用的
https://github.com/kubernetes/kops/blob/1f1b9fcece35654e3013544b6972083570bb09a6/docs/cluster_spec.md#containerregistry

而一旦kops安裝好之後，一般的kubectl deploy如果使用北京或寧夏region的ECR，不需要額外處理docker login的，這是k8s官方上游源代碼自帶就對ECR credentials and token management的支持。
https://github.com/kubernetes/kubernetes/blob/master/pkg/credentialprovider/aws/aws_credentials.go


你可以試著把你的image push到北京ECR，然後deploy一個應用指向你自己的北京ECR，你的deploymeng應可順利抓取ECR上面的景象，整個認證授權部分應該kubelet會幫你處理掉。

**Comment by pahud** [comment]
>如果不是配置make edit-cluster时设置ECR地址，那么在拉取ECR的image时该如何写yaml文件。
谢谢

如果你不做make edit-cluster這部分使用這段內容
https://github.com/nwcdlabs/kops-cn/blob/3cf848fe72fb3bf6c171a32b760208c64bd065c5/spec.yml#L1-L8

這樣Kops會認為你沒有本地安裝的image mirror，所有images都會往海外抓取，這樣很多images會抓不下來，kops集群會起不來。這就是為何要edit-cluster配置`containerRegistry`的原因。另一個`fileRepository`也是類似的目的。

**Comment by YuTingLiu** [comment]
@pahud 好的，多谢。
