### ISSUE TITLE
error when: kops edit cluster

### ISSUE THREAD

**Issue by dev-miali** [nwcdlabs/kops-cn#8]
kops edit cluster
tried to add:
   assets:
    containerRegistry: 937788672844.dkr.ecr.cn-north-1.amazonaws.com.cn
    fileRepository: https://s3.cn-north-1.amazonaws.com.cn/kops-bjs/fileRepository/
  docker:
    logDriver: ""
    registryMirrors:
        - https://registry.docker-cn.com

wq: to save, however ,editor re-opens and getting error:
error populating cluster spec: error building complete spec: options did not converge after 10 iterations
 
i tried to ignore and keep going to the final step  : kops validate cluster
unexpected error during validation: error listing nodes: Get https://api-cluster-zhy-k8s-local-qpbf7n-1465482247.cn-northwest-1.elb.amazonaws.com.cn/api/v1/nodes: EOF

go to aws console, find:
the three master instances out of service.
 i checked the security group rules are all right.
i already made icp exception for 80/8080/443 , and i can telnet elb:443.

and i googled it ,find similar issue: https://github.com/kubernetes/kops/issues/5061

how to fix it ?

**Comment by pahud** [comment]
Hi

you should paste the content under the `spec` and before `api` like this
![image](https://user-images.githubusercontent.com/278432/47897276-084ff880-deac-11e8-92db-b2fdf10e10b4.png)

and make sure `:wq!` with no error.

**Comment by dev-miali** [comment]
![](file:///Users/lilei/Desktop/Screen%20Shot%202018-11-02%20at%202.55.40%20PM.png)

yes, i pasted right there and got the error (find upper in the picture)

**Comment by dev-miali** [comment]
many thanks, after upgrading kops from 1.9.1 to 1.10.0,  the error gone  and successfully started a  5-node cluster.
