### ISSUE TITLE
instance group with on-demand and spot

### ISSUE THREAD

**Issue by pahud** [nwcdlabs/kops-cn#81]
kops 1.12.0開始支持instance group with mixed instance types，詳見上游官方文件
https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#creating-a-instance-group-of-mixed-instances-types-aws-only

這個配置方式將會使instance group後面的autoscaling group使用Launch Template來起ondemand+spot跨多個instance types與多個AZ的配置。關於這部分的AWS功能可以查看這裡
https://aws.amazon.com/blogs/aws/new-ec2-auto-scaling-groups-with-multiple-instance-types-purchase-options/

# 操作流程

參考`kops-cn`說明，`make create-cluster`與`make edit-cluster`完成

手動執行kops修改`nodes` instance group

```bash
$ export KOPS_STATE_STORE=s3://pahud-kops-state-store-zhy
$ export AWS_REGION=cn-northwest-1
$ export AWS_DEFAULT_REGION=$AWS_REGION
$ kops edit ig --name=cluster.zhy.k8s.local nodes
```
![image](https://user-images.githubusercontent.com/278432/58855436-aae68900-86d2-11e9-9af2-4aa378989e13.png)

For example

```bash
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-06-04T10:19:12Z
  labels:
    kops.k8s.io/cluster: cluster.zhy.k8s.local
  name: nodes
spec:
  image: ami-0cb93c9d844de0c18
  machineType: c5.large
  maxSize: 10
  minSize: 10
  mixedInstancesPolicy:
    instances:
    - m4.large
    - c4.xlarge
    - c4.large
    onDemandAboveBase: 0
    onDemandBase: 2
    spotInstancePools: 9
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - cn-northwest-1a
  - cn-northwest-1b
  - cn-northwest-1c
```

最後 

```bash
$ make update-cluster
```
# 查看EC2 autoscaling console
![image](https://user-images.githubusercontent.com/278432/58873161-44746180-86f8-11e9-8431-afb382828568.png)

**Comment by pahud** [comment]
这个模式目前看起来还有一些问题， node无法ready

![image](https://user-images.githubusercontent.com/278432/58881952-d5a20300-870d-11e9-9c53-191909e936f7.png)

**Comment by walkley** [comment]
kops的问题[kubernetes/kops#7091](https://github.com/kubernetes/kops/issues/7091) 已经被close了，对应的pr是[kubernetes/kops#7370](https://github.com/kubernetes/kops/pull/7370)

我刚才用最新的kops 1.13.0 + k8s v1.13.10测试，worker node正常工作，扩容spot fleet也正常工作

**Comment by pahud** [comment]
太棒了 @walkley  那我先close這個issue了
