### ISSUE TITLE
Improvement for kops readme

### ISSUE THREAD

**Issue by jansony1** [nwcdlabs/kops-cn#85]
As kops and kubernetes update very frequently and not all SA or customer familar with kops under the hood. 

We may add a reminder for  them to make sure **"Is their kops cli version stay up to date ?"** otherwise if they had install kops cli before, they may fail to install the latest kubernetes cluster .

**Comment by pahud** [comment]
更新了README，请看看是否足够清楚。
https://github.com/nwcdlabs/kops-cn
或者也欢迎你提交PR直接对README修改也可以。
