### ISSUE TITLE
【討論】 更換default AMI 使用Kops Debian官方AMI

### ISSUE THREAD

**Issue by pahud** [nwcdlabs/kops-cn#96]
根據[這個thread](https://github.com/nwcdlabs/kops-cn/issues/91#issuecomment-513112725)， 目前default CoreOS AMI存在穩定性問題，包括Amazon Linux 2 AMI也有尚未解決的問題，我準備把default AMI改成Kops官方Deiban AMI,  目前在`cn-north-1` and `cn-northwest-1`有看到這些Community AMI，但不確定是否為 `kope.io` 官方身分上傳 (參考[這裡官方說明](https://github.com/kubernetes/kops/blob/master/docs/images.md#images))

此外，根據[這裡](https://github.com/kubernetes/kops/blob/bb4574b1d572d5e453c3570ebe06127d0adc3bda/channels/stable#L29-L31)定義，目前建議版本應該是`kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13`, 但這個image目前在北京寧夏Region都還找不到。

下面這兩個AMI可以被找到，但不確定是不是KOPS官方AMI，有可能是其他用戶自己打包上傳的，可能存在一些疑慮。

**cn-north-1 ami-076828ef599fb3764**
![image](https://user-images.githubusercontent.com/278432/61573591-ef43b200-aae3-11e9-8da0-f996855729de.png)

**cn-northwest-1 ami-0b46e70fdcdae1aef**
![image](https://user-images.githubusercontent.com/278432/61573609-18fcd900-aae4-11e9-89b4-95c1f6ef8598.png)

**Comment by pahud** [comment]
正在根據[這篇文件](https://stackoverflow.com/questions/36461042/how-to-copy-an-ami-from-ireland-region-to-china-region-in-aws)說明，將海外 `kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13` 這個kops default platform image搬到CN來試試看。

ref: https://github.com/kubernetes/kops/blob/bb4574b1d572d5e453c3570ebe06127d0adc3bda/channels/stable#L29-L31

**Comment by pahud** [comment]
已把海外官方鏡像搬進來，寧夏運行正常

![image](https://user-images.githubusercontent.com/278432/61576388-2c239f00-ab0c-11e9-9e0f-2877d29f0b81.png)

有興趣可以試試看

cn-north-1 AMI ?= **ami-03b02f476f48beeed**
cn-northwest=1 AMI ?= **ami-039cfa346d0777968**

**Comment by guohenghaha** [comment]
我们最近新建集群的时候也遇到了这种情况，准备用你发的新AMI试试，不过我有个疑问，因为我们的新集群已经创建了，我要更改AMI是不是必须得把现在的集群删除重新创建呢还是可以edit然后update。

**Comment by pahud** [comment]
更新了AMI

- 把/etc/apt/sources.list更換成了國內的mirror，否則master無法**InService**

https://github.com/nwcdlabs/kops-cn/commit/43e8d6a20ab319c570ab41601dc4b3e17f24b841

已修改Makefile，現在開始改用Debian AMI
```
ifeq ($(TARGET_REGION) ,cn-north-1)
	CLUSTER_NAME ?= cluster.bjs.k8s.local
	# copy from kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13
	# see https://github.com/nwcdlabs/kops-cn/issues/96
	AMI ?= ami-02dd4d384eb0e0b3a
	ZONES ?= cn-north-1a,cn-north-1b
endif

ifeq ($(TARGET_REGION) ,cn-northwest-1)
	CLUSTER_NAME ?= cluster.zhy.k8s.local
	# copy from kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13
	# see https://github.com/nwcdlabs/kops-cn/issues/96
	AMI ?= ami-068b32c3754324d44
	ZONES ?= cn-northwest-1a,cn-northwest-1b,cn-northwest-1c
endif
```

**Comment by pahud** [comment]
實際測試，搭配最新kops-1.12.3沒問題

see https://github.com/nwcdlabs/kops-cn/issues/99

**Comment by pahud** [comment]
Debian AMI shipped.

**Comment by pahud** [comment]
@guohenghaha 

我建議重新創建。

**Comment by pahud** [comment]
**k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-06-21** 已複製進來國內

cn-north-1 **ami-066a77b2ea1486386**
cn-northwest-1 **ami-07fb7a3af7dcb813b**

歡迎測試。
