### ISSUE TITLE
can't create the cluster

### ISSUE THREAD

**Issue by hhuchzh** [nwcdlabs/kops-cn#98]
when I use the latest code to build cluster in cn-northwest-1, the AWS resouce can create successful, but I cann't validate he cluster, then I ssh into the master, I found there has no docker images and no process about kubernetes component. the similar situation is on the node.
anyone konw what's the problem?

**Comment by pahud** [comment]
try this https://github.com/nwcdlabs/kops-cn/issues/99 with Debian AMI

**Comment by pahud** [comment]
暫時關閉這個issue，如果用最新的Makefile裡面的AMI還有問題再reopen回報，謝謝！
