### ISSUE TITLE
kops 1.12.3 已可用

### ISSUE THREAD

**Issue by pahud** [nwcdlabs/kops-cn#99]
https://github.com/kubernetes/kops/releases/tag/1.12.3

just released with recommendedVersion 1.12.9

https://github.com/kubernetes/kops/blob/ac6392a24d9f471da7c684521cc5f27c8c802732/channels/stable#L45-L47

- [x] mirror required fileRepository
- [x] mirror required images
- [x] update README
- [x] provide official Debian AMI with local `/etc/apt/sources.list` from china mirror
- [x] validate cn-north-1
- [x] validate cn-northwest-1

**Comment by pahud** [comment]
<img width="829" alt="圖片" src="https://user-images.githubusercontent.com/278432/62393948-55c5d700-b59e-11e9-9df9-5943b6add049.png">

可以用了。

cn-north-1 	AMI ?= ami-02dd4d384eb0e0b3a
cn-northwest-1 	AMI ?= ami-068b32c3754324d44

**Comment by pahud** [comment]
shipped

**Comment by guohenghaha** [comment]
@pahud 我看到你的截图列出来的时间是创建几分钟之后的截图，有没有测试过集群运行5个小时以上的时候是否中间出现过Node NotReady的状态呢？

**Comment by pahud** [comment]
@guohenghaha 之前用CoreOS AMI的時候有人回報這個現象
https://github.com/nwcdlabs/kops-cn/issues/91
所以這次決定改成官方的Debian AMI
https://github.com/nwcdlabs/kops-cn/issues/96

再麻煩測試一下我昨天更新的這個版本吧！Makefile裡面定義的AMI也都用Debian了。
